site_name: Active InferAnts
repo_url: https://github.com/ActiveInferenceInstitute/ActiveInferAnts
theme:
  name: material
nav:
  - Home: index.md
  - Architecture:
      - architecture/README.md
  - API:
      - api/README.md
  - Concepts:
      - concepts/README.md
  - Guides:
      - guides/README.md
  - Operations:
      - operations/README.md
  - Reference:
      - reference/README.md
  - Security:
      - security/README.md
  - Systems:
      - systems/README.md
  - Testing:
      - testing/README.md
  - Tutorials:
      - tutorials/README.md
